apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pipeline-auth
stringData:
  # URL to the Azure DevOps organization
  AZP_URL: https://dev.azure.com/<org>

  # PAT with scope "Agent Pools - Read & manage"
  AZP_TOKEN: <pat>

  # Agent Pool needs to be the same as in the ScaledJob
  AZP_POOL: Default