name: Docker Hub Standard Image CI

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: jamesdkelly88
  DOCKER_IMAGE: azure-pipelines-agent

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./container-image
          file: ./container-image/Dockerfile
          push: true
          tags: |
           ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
           ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:jammy
           ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:jammy-standard
           ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:standard
